# Generated by Django 4.1.3 on 2024-02-16 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpalapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firebase_uid',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
