# Generated by Django 4.1.3 on 2024-02-17 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpalapi', '0002_rename_firebase_uid_user_uid_remove_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projectpalapi.project'),
        ),
    ]
