# Generated by Django 4.1.3 on 2024-02-17 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpalapi', '0003_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projectpalapi.category'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='projectpalapi.task'),
        ),
    ]
